package com.cuzz.springaidemo.models.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class DocumentDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.id
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.document_name
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    @JsonProperty("name")
    private String documentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.create_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.update_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.content
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.id
     *
     * @return the value of documents.id
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.id
     *
     * @param id the value for documents.id
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.document_name
     *
     * @return the value of documents.document_name
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.document_name
     *
     * @param documentName the value for documents.document_name
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName == null ? null : documentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.create_time
     *
     * @return the value of documents.create_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.create_time
     *
     * @param createTime the value for documents.create_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.update_time
     *
     * @return the value of documents.update_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.update_time
     *
     * @param updateTime the value for documents.update_time
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.content
     *
     * @return the value of documents.content
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.content
     *
     * @param content the value for documents.content
     *
     * @mbg.generated Thu Apr 10 21:19:00 CST 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}