package com.cuzz.springaidemo.models.dto;

import java.util.Date;

public class RoleKnowledgeDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_knowledge.id
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_knowledge.role_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_knowledge.knowledge_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    private String knowledgeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_knowledge.create_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_knowledge.update_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_knowledge.id
     *
     * @return the value of role_knowledge.id
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_knowledge.id
     *
     * @param id the value for role_knowledge.id
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_knowledge.role_name
     *
     * @return the value of role_knowledge.role_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_knowledge.role_name
     *
     * @param roleName the value for role_knowledge.role_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_knowledge.knowledge_name
     *
     * @return the value of role_knowledge.knowledge_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public String getKnowledgeName() {
        return knowledgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_knowledge.knowledge_name
     *
     * @param knowledgeName the value for role_knowledge.knowledge_name
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public void setKnowledgeName(String knowledgeName) {
        this.knowledgeName = knowledgeName == null ? null : knowledgeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_knowledge.create_time
     *
     * @return the value of role_knowledge.create_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_knowledge.create_time
     *
     * @param createTime the value for role_knowledge.create_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_knowledge.update_time
     *
     * @return the value of role_knowledge.update_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_knowledge.update_time
     *
     * @param updateTime the value for role_knowledge.update_time
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}