package com.cuzz.springaidemo.mapper;

import com.cuzz.springaidemo.models.dto.DocumentDTO;
import com.cuzz.springaidemo.models.dto.DocumentDTOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface DocumentDTOMapper {


    //document_name加索引
    @Select({
            "SELECT document_name FROM documents"
    })
    List<String> getAllDocumentName();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    long countByExample(DocumentDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int deleteByExample(DocumentDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int insert(DocumentDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int insertSelective(DocumentDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    List<DocumentDTO> selectByExample(DocumentDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    DocumentDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int updateByExampleSelective(@Param("row") DocumentDTO row, @Param("example") DocumentDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int updateByExample(@Param("row") DocumentDTO row, @Param("example") DocumentDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int updateByPrimaryKeySelective(DocumentDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Sep 04 22:12:49 CST 2025
     */
    int updateByPrimaryKey(DocumentDTO row);
}