package com.cuzz.springaidemo.mapper;

import com.cuzz.springaidemo.models.dto.RoleKnowledgeDTO;
import com.cuzz.springaidemo.models.dto.RoleKnowledgeDTOExample;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoleKnowledgeDTOMapper {





    @Insert({
            "<script>",
            "INSERT INTO role_knowledge (role_name, knowledge_name, create_time, update_time) VALUES",
            "<foreach collection='list' item='knowledge' separator=','>",
            "(#{roleName}, #{knowledge}, NOW(), NOW())",
            "</foreach>",
            "ON CONFLICT (role_name, knowledge_name) DO NOTHING",
            "</script>"
    })
    long batchAddRoleKnowledge(@Param("list") List<String> knowledge, @Param("roleName") String roleName);








    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    long countByExample(RoleKnowledgeDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int deleteByExample(RoleKnowledgeDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int insert(RoleKnowledgeDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int insertSelective(RoleKnowledgeDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    List<RoleKnowledgeDTO> selectByExample(RoleKnowledgeDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    RoleKnowledgeDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int updateByExampleSelective(@Param("row") RoleKnowledgeDTO row, @Param("example") RoleKnowledgeDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int updateByExample(@Param("row") RoleKnowledgeDTO row, @Param("example") RoleKnowledgeDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int updateByPrimaryKeySelective(RoleKnowledgeDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_knowledge
     *
     * @mbg.generated Thu Apr 10 21:18:22 CST 2025
     */
    int updateByPrimaryKey(RoleKnowledgeDTO row);
}