package com.cuzz.springaidemo.mapper;

import com.cuzz.springaidemo.models.dto.RoleDTO;
import com.cuzz.springaidemo.models.dto.RoleDTOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RoleDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    long countByExample(RoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int deleteByExample(RoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int insert(RoleDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int insertSelective(RoleDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    List<RoleDTO> selectByExample(RoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    RoleDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int updateByExampleSelective(@Param("row") RoleDTO row, @Param("example") RoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int updateByExample(@Param("row") RoleDTO row, @Param("example") RoleDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int updateByPrimaryKeySelective(RoleDTO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbg.generated Thu Apr 10 21:18:02 CST 2025
     */
    int updateByPrimaryKey(RoleDTO row);
}